project:
  type: website
  output-dir: docs

website:
  title: "Plant App"
  favicon: media/pics/pflanzen.png
  navbar:
    right:
      - href: index.qmd
        text: Home
      - features.qmd

format:
  html:
    theme:
      - superhero
      - brand
    css: styles.css
    toc: true



